[build]
  publish = "."

[build.environment]
  SECRETS_SCAN_SMART_DETECTION_ENABLED = "false"

[functions]
  directory = "netlify/functions"

[functions."daily-reminders"]
  schedule = "0 0 * * *"

[functions."sync-budget"]
  schedule = "0 12 * * *"

[[redirects]]
  from = "/firebase-messaging-sw.js"
  to = "/firebase-messaging-sw.js"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
